In [1]:
import numpy as np
print(np.__version__)

1.20.2


In [7]:
#1-D array
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#boolean array
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
np.full((3, 3), False, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [10]:
#odd numbers
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [11]:
#even numbers
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

In [12]:
#replacing values
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
#reshaping an array
arr = np.arange(10)
arr.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
#stacking arrays vertically 
a = np.arange(10).reshape(2,-1)
b = np.arange(10).reshape(2,-1)
np.vstack([a, b])
np.concatenate([a, b], axis=0)
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
#stacking arrays horizontally
np.hstack([a, b])
np.concatenate([a, b], axis=1)
np.c_[a, b]

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [21]:
#intersecting
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [22]:
#set difference
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [23]:
#return index upon condition 
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [24]:
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]


array([ 5,  6,  7,  8,  9, 10])

In [27]:
#maximum function for pairs
def maxx(x, y):
    
    if x >= y:
        return x
    else:
        return y


pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [28]:
#swapping two columns
arr = np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [30]:
#swapping two rows
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [31]:
#reversing columns 
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [16]:
#create a 2D array containing random floats
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[7.6243678  7.54677274 9.05244015]
 [8.42158453 5.23456234 5.13114048]
 [5.2160579  9.11578583 9.27492892]
 [5.88154752 9.53908974 7.61204639]
 [8.61063152 9.39584903 7.05289229]]


In [19]:
#print only 3 decimal places in python
np.set_printoptions(precision=3)
rand_arr[:4]

array([[7.624, 7.547, 9.052],
       [8.422, 5.235, 5.131],
       [5.216, 9.116, 9.275],
       [5.882, 9.539, 7.612]])

In [20]:
#limit number of items displayed
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [25]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[1, 5, 1, 5, 6],
        [8, 6, 4, 5, 0],
        [8, 9, 8, 3, 8],
        [8, 8, 4, 0, 0]],

       [[0, 9, 8, 2, 4],
        [1, 4, 7, 3, 0],
        [3, 1, 1, 6, 9],
        [5, 5, 4, 0, 3]],

       [[7, 7, 1, 9, 6],
        [7, 2, 2, 6, 1],
        [0, 6, 9, 3, 1],
        [0, 0, 4, 1, 1]]])

In [30]:
#concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3, ..., 21, 21, 21])

In [31]:
#grid concatenation
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [32]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [33]:
#vertical stack
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [34]:
#horizontal stack
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

In [36]:
#splitting data
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)

[3 4 5] [] []


In [37]:
grid = np.arange(16).reshape((4,4))
upper,lower = np.vsplit(grid,[2])
print (upper, lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [39]:
np.zeros(10, dtype='int')


array([0, 0, 0, ..., 0, 0, 0])

In [40]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.arange(0, 20, 2)

array([ 0,  2,  4, ..., 14, 16, 18])

In [42]:
#random data
np.random.normal(0, 1, (3,3))

array([[-0.404,  0.546, -1.075],
       [-1.135, -0.881,  0.707],
       [ 0.113, -1.98 , -1.636]])

In [43]:
x3 = np.random.randint(10, size=(3,4,5)) #three dimension


print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


In [44]:
#array
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [45]:
#array slicing
x = np.arange(10)
x

array([0, 1, 2, ..., 7, 8, 9])

In [47]:
x[4:7]


array([4, 5, 6])

In [48]:
x[: : 3]

array([0, 3, 6, 9])

In [49]:
x[: : 2]

array([0, 2, 4, 6, 8])

In [50]:
x[: : -1]

array([9, 8, 7, ..., 2, 1, 0])

In [51]:
x[:5]

array([0, 1, 2, 3, 4])

In [52]:
x[4:]

array([4, 5, 6, 7, 8, 9])

In [53]:
x[1::2]

array([1, 3, 5, 7, 9])