In [2]:
#series
import pandas as pd
series1 = pd.Series ([1,2], index = ['a', 'b'])
series1

a    1
b    2
dtype: int64

In [4]:
series1.values

array([1, 2], dtype=int64)

In [6]:

series1[['b','a']]

b    2
a    1
dtype: int64

In [7]:
series1.index

Index(['a', 'b'], dtype='object')

In [9]:
series2 = series1.unique()
series2

array([1, 2], dtype=int64)

In [10]:
series1 + series2

a    2
b    4
dtype: int64

In [11]:
#dataframe
dict1 = {'state': ['Ohio',
'CA'], 'year': [2000, 2010]}
df1 = pd.DataFrame(dict1)
df1

state  year
0  Ohio  2000
1    CA  2010

In [14]:
df1 = pd.DataFrame(dict1,index = ['row1', 'row2'])
df1

state  year
row1  Ohio  2000
row2    CA  2010

In [16]:
df1 = pd.DataFrame(dict1,columns = ['year', 'state'])
df1

year state
0  2000  Ohio
1  2010    CA

In [17]:
dict1 = {'col1': {'row1': 1,'row2': 2}, 'col2': {'row1':3, 'row2': 4} }
df1 = pd.DataFrame(dict1)
df1

col1  col2
row1     1     3
row2     2     4

In [18]:
df1.index

Index(['row1', 'row2'], dtype='object')

In [19]:
df1.columns

Index(['col1', 'col2'], dtype='object')

In [20]:
df1.values

array([[1, 3],
       [2, 4]], dtype=int64)

In [29]:
df1.T

row1  row2
col1     1     2
col2     3     4

In [40]:
df1 = pd.DataFrame(dict1,columns = ['year', 'state'])
del df1['year']
df1

Empty DataFrame
Columns: [state]
Index: []

In [41]:
dict1 = {'state': ['Ohio','CA'], 'year': [2000, 2010]}
df1 = pd.DataFrame(dict1,columns = ['year', 'state'])
df1['eastern'] = df1.state == 'Ohio'
df1

year state  eastern
0  2000  Ohio     True
1  2010    CA    False

In [42]:
df1['state']

0    Ohio
1      CA
Name: state, dtype: object

In [ ]:
#panel data (3D)
import numpy as np
import pandas as pd
data = { 'item1': pd.DataFrame(np.random.randn(4,3)),'item2': pd.DataFrame(np.random.randn(4,2))}
p=pd.Panel(data)
p

In [ ]:
#stack Dataframe
import pandas_datareader.data as web
from pandas import Panel
panel1 = Panel({stk : web.get_data_yahoo(stk, '1/1/2000', '1/1/2010')
for stk in ['AAPL', 'IBM']})
panel1 = panel1.swapaxes('item', 'minor')
panel1.ix[:, '6/1/2003', :].to_frame()

In [3]:
print(pd.__version__)
print(np.__version__)


1.2.4
1.20.2


In [8]:
#index objects
import numpy as np
import pandas as pd
series1 = pd.Series(np.random.randn(6), index = [['a', 'a', 'a', 'b', 'b', 'b'], [1, 2, 3,1, 2, 3]])
series1.index.names = ['key1', 'key2']
series1

key1  key2
a     1       0.999359
      2       0.617226
      3      -0.204723
b     1       1.391633
      2      -1.418502
      3       0.060635
dtype: float64

In [9]:
series1['b']

key2
1    1.391633
2   -1.418502
3    0.060635
dtype: float64

In [10]:
series1[:, 2] 

key1
a    0.617226
b   -1.418502
dtype: float64

In [16]:
series1.swaplevel('key1', 'key2')


key2  key1
1     a       0.999359
2     a       0.617226
3     a      -0.204723
1     b       1.391633
2     b      -1.418502
3     b       0.060635
dtype: float64

In [22]:
series1 = pd.Series(np.random.randn(6), index = [['b', 'b', 'b', 'a', 'a', 'a'], [1, 2, 3,1, 2, 3]])
series1.index.names = ['key1', 'key2']
series1.sort_index()

key1  key2
a     1      -1.790853
      2       0.034315
      3       2.038359
b     1       1.194045
      2       0.057803
      3      -0.049114
dtype: float64

In [23]:
series1.sum(level = 'key2')

key2
1   -0.596807
2    0.092117
3    1.989245
dtype: float64

In [30]:
df1.set_index(['state','year'])

Empty DataFrame
Columns: []
Index: [(Ohio, 2000), (CA, 2010)]

In [31]:
df1.reset_index()

index  year state
0      0  2000  Ohio
1      1  2010    CA

In [32]:
#missing data
df1.isnull()

year  state
0  False  False
1  False  False

In [33]:
df1.notnull()

year  state
0  True   True
1  True   True

In [36]:
df1.dropna()

year state
0  2000  Ohio
1  2010    CA

In [37]:
df1.dropna(how = 'all')

year state
0  2000  Ohio
1  2010    CA

In [38]:
df1.dropna(axis = 1)

year state
0  2000  Ohio
1  2010    CA

In [41]:
df1.fillna(0)

year state
0  2000  Ohio
1  2010    CA

In [42]:
df1.fillna('inplace = True')

year state
0  2000  Ohio
1  2010    CA

In [43]:
df1.fillna({'col1' : 0, 'col2' : -1})

year state
0  2000  Ohio
1  2010    CA

In [44]:
df1.fillna(method = 'ffill', limit = 2)

year state
0  2000  Ohio
1  2010    CA

In [49]:
#indexing by columns
df1['year']

0    2000
1    2010
Name: year, dtype: int64

In [55]:
df1['state']

0    Ohio
1      CA
Name: state, dtype: object

In [61]:
#boolean indexing
df1[ [True, False] ]
df1[df1['year'] > 2000]

year state
1  2010    CA

In [65]:
#dropping 
df1.drop('state',axis=1)

year
0  2000
1  2010

In [67]:
#reindexing 
date_index = pd.date_range('01/23/2010',periods = 10, freq = 'D')
df1.reindex(date_index)

year state
2010-01-23   NaN   NaN
2010-01-24   NaN   NaN
2010-01-25   NaN   NaN
2010-01-26   NaN   NaN
2010-01-27   NaN   NaN
2010-01-28   NaN   NaN
2010-01-29   NaN   NaN
2010-01-30   NaN   NaN
2010-01-31   NaN   NaN
2010-02-01   NaN   NaN

In [68]:
df1.reindex(date_index,fill_value = 0)

year state
2010-01-23     0     0
2010-01-24     0     0
2010-01-25     0     0
2010-01-26     0     0
2010-01-27     0     0
2010-01-28     0     0
2010-01-29     0     0
2010-01-30     0     0
2010-01-31     0     0
2010-02-01     0     0

In [69]:
df1.reindex(columns = ['a', 'b'])

a   b
0 NaN NaN
1 NaN NaN

In [75]:
#sorting index
series1.sort_index()

key1  key2
a     1      -1.790853
      2       0.034315
      3       2.038359
b     1       1.194045
      2       0.057803
      3      -0.049114
dtype: float64

In [81]:
#rank
series1.rank()

key1  key2
b     1       5.0
      2       4.0
      3       2.0
a     1       1.0
      2       3.0
      3       6.0
dtype: float64

In [82]:
df1.rank(axis = 1)

year
0   1.0
1   1.0

In [8]:
#lambda function
x = lambda a : a + 10
print(x(5)) 

15


In [11]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))

22


In [13]:
#assign function
import pandas as pd
values= [['Rohan',455],['Elvish',250],['Deepak',495],['Soni',400],['Radhika',350],['Vansh',450]] 
df = pd.DataFrame(values,columns=['Name','Total_Marks'])
df = df.assign(Percentage = lambda x: (x['Total_Marks'] /500 * 100))
df

Name  Total_Marks  Percentage
0    Rohan          455        91.0
1   Elvish          250        50.0
2   Deepak          495        99.0
3     Soni          400        80.0
4  Radhika          350        70.0
5    Vansh          450        90.0

In [16]:
#apply function
import pandas as pd
import numpy as np
  

values_list = [[15, 2.5, 100], [20, 4.5, 50], [25, 5.2, 80],
               [45, 5.8, 48], [40, 6.3, 70], [41, 6.4, 90], 
               [51, 2.3, 111]]
  

df = pd.DataFrame(values_list, columns=['Field_1', 'Field_2', 'Field_3'],
                  index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
  
df = df.apply(lambda x: np.square(x) if x.name == 'd' else x, axis=1)
df
  


Field_1  Field_2  Field_3
a     15.0     2.50    100.0
b     20.0     4.50     50.0
c     25.0     5.20     80.0
d   2025.0    33.64   2304.0
e     40.0     6.30     70.0
f     41.0     6.40     90.0
g     51.0     2.30    111.0

In [17]:
#unique and counts
df1.index.is_unique #• pd.value_counts() returns value frequency.

True

In [21]:
df1.value_counts

<bound method DataFrame.value_counts of    year state
0  2000  Ohio
1  2010    CA>

In [26]:
#groupby function
df.groupby('Field_2').mean()

Field_1  Field_3
Field_2                  
2.30        51.0    111.0
2.50        15.0    100.0
4.50        20.0     50.0
5.20        25.0     80.0
6.30        40.0     70.0
6.40        41.0     90.0
33.64     2025.0   2304.0

In [27]:
df.groupby([df['Field_1'],df['Field_2']]).mean()

Field_3
Field_1 Field_2         
15.0    2.50       100.0
20.0    4.50        50.0
25.0    5.20        80.0
40.0    6.30        70.0
41.0    6.40        90.0
51.0    2.30       111.0
2025.0  33.64     2304.0

In [33]:
#groupby object
df.groupby('Field_1')['Field_2']

In [36]:
df['Field_1'].groupby(df['Field_2'])


In [42]:
#iteration in groupby
for name, groupdata in df.groupby('Field_2'):
    print(name)

2.3
2.5
4.5
5.2
6.3
6.4
33.64


In [43]:
print(groupdata)

   Field_1  Field_2  Field_3
d   2025.0    33.64   2304.0


In [48]:
#group to dict
dict(list(df.groupby('Field_2')))

{2.3:    Field_1  Field_2  Field_3
 g     51.0      2.3    111.0,
 2.5:    Field_1  Field_2  Field_3
 a     15.0      2.5    100.0,
 4.5:    Field_1  Field_2  Field_3
 b     20.0      4.5     50.0,
 5.2:    Field_1  Field_2  Field_3
 c     25.0      5.2     80.0,
 6.3:    Field_1  Field_2  Field_3
 e     40.0      6.3     70.0,
 6.4:    Field_1  Field_2  Field_3
 f     41.0      6.4     90.0,
 33.64:    Field_1  Field_2  Field_3
 d   2025.0    33.64   2304.0}

In [50]:
#group columns
grouped = df.groupby(df.dtypes, axis = 1)
dict(list(grouped))

{dtype('float64'):    Field_1  Field_2  Field_3
 a     15.0     2.50    100.0
 b     20.0     4.50     50.0
 c     25.0     5.20     80.0
 d   2025.0    33.64   2304.0
 e     40.0     6.30     70.0
 f     41.0     6.40     90.0
 g     51.0     2.30    111.0}

In [51]:
#grouping with functions
df.groupby(len).sum()

Field_1  Field_2  Field_3
1   2217.0    60.84   2805.0

In [59]:
#aggregate functions 
import pandas as pd
import numpy as np

df = pd.DataFrame([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9],

                   [np.nan, np.nan, np.nan]],

                  columns=['A', 'B', 'C'])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [65]:
df.agg(['sum', 'min','max','mean'])

A     B     C
sum   12.0  15.0  18.0
min    1.0   2.0   3.0
max    7.0   8.0   9.0
mean   4.0   5.0   6.0

In [66]:
#transform function
df = pd.DataFrame({'A': range(3), 'B': range(1, 4)})
df

A  B
0  0  1
1  1  2
2  2  3

In [67]:
df.transform(lambda x: x + 1)

A  B
0  1  2
1  2  3
2  3  4

In [68]:
df = pd.DataFrame({

    "Date": [

        "2015-05-08", "2015-05-07", "2015-05-06", "2015-05-05",

        "2015-05-08", "2015-05-07", "2015-05-06", "2015-05-05"],

    "Data": [5, 8, 6, 1, 50, 100, 60, 120],

})

df


Date  Data
0  2015-05-08     5
1  2015-05-07     8
2  2015-05-06     6
3  2015-05-05     1
4  2015-05-08    50
5  2015-05-07   100
6  2015-05-06    60
7  2015-05-05   120

In [70]:
df.groupby('Date')['Data'].transform('sum')

0    5
1    8
2    6
3    1
4    5
5    8
6    6
7    1
Name: Data, dtype: int64

In [3]:
#merging data
import pandas as pd
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [5]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})
df2

key  data2
0   a      0
1   b      1
2   d      2

In [6]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [7]:
pd.merge(df1, df2, how='inner')  

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [8]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                  'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
pd.merge(left1, right1, left_on='key', right_index=True) 

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [10]:
left1.join(right1, how='outer')

key  value  group_val
0    a    0.0        NaN
1    b    1.0        NaN
2    a    2.0        NaN
3    a    3.0        NaN
4    b    4.0        NaN
5    c    5.0        NaN
a  NaN    NaN        3.5
b  NaN    NaN        7.0

In [13]:
left1.join(right1, on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [15]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])  

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [16]:
pd.concat([s1, s2, s3], axis=1)  

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [18]:
#data cleaning
import numpy as np
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
           index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
           index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [20]:
pd.isnull(a)

f     True
e    False
d     True
c    False
b    False
a     True
dtype: bool

In [21]:
pd.isnull(b)

f    False
e    False
d    False
c    False
b    False
a     True
dtype: bool

In [22]:
#combining data
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                 'b': [np.nan, 2., np.nan, 6.],
                 'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
                 'b': [np.nan, 3., 4., 6., 8.]})
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [23]:
#reshaping data
data = df1.stack()
data

0  a     1.0
   c     2.0
1  b     2.0
   c     6.0
2  a     5.0
   c    10.0
3  b     6.0
   c    14.0
dtype: float64

In [24]:
data.unstack()  

a    b     c
0  1.0  NaN   2.0
1  NaN  2.0   6.0
2  5.0  NaN  10.0
3  NaN  6.0  14.0

In [27]:
#removing duplicates
data = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [28]:
data.duplicated() 

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [29]:
data.drop_duplicates()   

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [31]:
#Mapping data
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
                           'corned beef', 'Bacon', 'pastrami', 'honey ham',
                           'nova lox'],
                  'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [32]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)   

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [34]:
#replacing data
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [35]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [36]:
#indexing data
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                 index=['Ohio', 'Colorado', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [37]:
data.index.map(str.upper)  

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [40]:
#renaming data
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [42]:
data.rename( columns={'three': 'peekaboo'})

one  two  peekaboo  four
Ohio        0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [44]:
#counting values
cats = [1,2,3,4,4,8,8,8,6,7]
pd.value_counts(cats)

8    3
4    2
1    1
2    1
3    1
6    1
7    1
dtype: int64

In [46]:
#generating random data
np.random.seed(12345)
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [47]:
#permutation
sampler = np.random.permutation(5)   #sampler에 랜덤하게 5개의 수를 배열
sampler

array([1, 0, 2, 3, 4])

In [49]:
#get dummies
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                'data1': range(6)})
pd.get_dummies(df['key'])  

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0